name: controlbs_mobile
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  calendar_date_picker2: ^0.5.5

  http: ^1.1.0

  provider: ^6.1.2

  dartz: ^0.10.1
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.2.0
  get_it: ^7.6.7
  go_router: ^13.1.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
