name: controlbs_mobile
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  calendar_date_picker2: ^0.5.5

  http: ^1.1.0

  provider: ^6.1.2

  dartz: ^0.10.1
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.2.0
  get_it: ^7.6.7
  go_router: ^14.2.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  collection: ^1.17.1
  geolocator: ^11.0.0
  encrypt: ^5.0.3
  network_info_plus: ^5.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.1.6
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  hand_signature: ^3.0.3
  path_provider: ^2.1.1
  file_picker: ^6.0.0
  document_file_save_plus: ^2.0.0
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
