// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1irF8OaVVaJEQIjjms2Z1Izxatu9JOQ',
    appId: '1:176266232310:web:8389e2ad06529772ccc7d7',
    messagingSenderId: '176266232310',
    projectId: 'fcm-controlbs',
    authDomain: 'fcm-controlbs.firebaseapp.com',
    storageBucket: 'fcm-controlbs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLxQuzh6Rp_TNHW1vPLZYXK_ktwSRxgs',
    appId: '1:176266232310:android:3ad2022ad8f9083accc7d7',
    messagingSenderId: '176266232310',
    projectId: 'fcm-controlbs',
    storageBucket: 'fcm-controlbs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1jb9q1CaeJQJKRRkVwahdh7nJGsz7FY',
    appId: '1:176266232310:ios:a01d74c9f914068accc7d7',
    messagingSenderId: '176266232310',
    projectId: 'fcm-controlbs',
    storageBucket: 'fcm-controlbs.appspot.com',
    iosBundleId: 'com.example.controlbsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo1jb9q1CaeJQJKRRkVwahdh7nJGsz7FY',
    appId: '1:176266232310:ios:a01d74c9f914068accc7d7',
    messagingSenderId: '176266232310',
    projectId: 'fcm-controlbs',
    storageBucket: 'fcm-controlbs.appspot.com',
    iosBundleId: 'com.example.controlbsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY1irF8OaVVaJEQIjjms2Z1Izxatu9JOQ',
    appId: '1:176266232310:web:124f21ab2a4dd4c4ccc7d7',
    messagingSenderId: '176266232310',
    projectId: 'fcm-controlbs',
    authDomain: 'fcm-controlbs.firebaseapp.com',
    storageBucket: 'fcm-controlbs.appspot.com',
  );
}
